### ISSUE TITLE
Glossar: Aufgabenschwierigkeit

### ISSUE THREAD

**Issue by Famondir** [dbuschhue/P4-Worflow#3]
Ich schlage vor, die im Glossar befindliche Beschreibung der Aufgabenschwierigkeit mit dem Hinweis zu versehen, dass es sich hierbei um die Interpretation entsprechend der IRT handelt. Daneben gibt es aus der KTT ja noch die Definition:
Itemschwierigkeit = Prozentanteil der Itemlösung, wobei 0 ein schweres Item ist und 1 ein super leichtes. (Darum hätte man den Index auch eher Leichtigkeit nennen sollen.)

Grüße, Simon

**Comment by marvrost** [comment]
Danke für den Erweiterungshinweis! Die Differenzierung ist sinnvoll und die Änderung wird spätestens im Dezember eingepflegt.

**Comment by marvrost** [comment]
Änderungsvorschlag angenommen & Dokument angepasst.
