### ISSUE TITLE
Glossar: ICC

### ISSUE THREAD

**Issue by Famondir** [dbuschhue/P4-Worflow#4]
Ich schlage vor, die im Glossar befindliche Beschreibung der ICCs anzupassen. Die ICC ist meines Verständnisses nach nur die Kurve, an der man dann Aufgabenschwierigkeit, Trennschärfe/Steigung und Pseudorateparameter ablesen kann. Das Abtragen der gruppenbasierten Lösungshäufigkeiten ist aber zur erwähnten Modellpassungsprüfung wichtig und sollte weiterhin beschrieben werden.

Wie sehr wollt ihr dabei ins Detail? Man kann die Gruppen ja anhand der Rohsummenwerte oder anhand der vom Modell vorhergesagten Personenfertigkeiten bilden. So ein Glossar soll ja sicher schlank bleiben. Aber weiterführende Links fände cih super gut.

Außerdem steht ICC im Kontext hierarchischer Modell noch für Intraclass Correlation Coefficient. [Übersichtsseite](https://www.theanalysisfactor.com/the-intraclass-correlation-coefficient-in-mixed-models/) und [Artikel mit Generalisierung für mehr als zwei Ebenen](https://largescaleassessmentsineducation.springeropen.com/articles/10.1186/s40536-018-0061-2)

Grüße, Simon

**Comment by marvrost** [comment]
Danke für die Begriffsdifferenzierung! Die Gruppen werden meines Wissens nach, nach gemittelten Personenfähigkeiten (die Plot-Funktion dokumentiert WLE-Schätzungen) gebildet. Eine entsprechende Texterweiterung wird spätestens im Dezember eingepflegt.

**Comment by marvrost** [comment]
Änderungsvorschlag angenommen & Dokument angepasst.
